float64 x #m/s
float64 y #m/s
float64 rot #rad/s
bool field_relative #field relative direction, as in x is always on the long side
bool open_loop #control drive motors without pid, just full send based on MAX_SPEED
---
---
